[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "blockeye-edge-functions"

[services.variables]
PORT = "3000"
NODE_ENV = "production"
